// Generated by svd2swift.

import MMIO

/// Flexible memory controller
nonisolated(unsafe) public let fmc = FMC(unsafeAddress: 0xa0000000)

/// General-purpose I/Os
nonisolated(unsafe) public let gpioa = GPIOA(unsafeAddress: 0x40020000)

/// General-purpose I/Os
nonisolated(unsafe) public let gpiob = GPIOB(unsafeAddress: 0x40020400)

/// General-purpose I/Os
nonisolated(unsafe) public let gpioc = GPIOC(unsafeAddress: 0x40020800)

/// General-purpose I/Os
nonisolated(unsafe) public let gpiod = GPIOD(unsafeAddress: 0x40020c00)

/// General-purpose I/Os
nonisolated(unsafe) public let gpioe = GPIOE(unsafeAddress: 0x40021000)

/// General-purpose I/Os
nonisolated(unsafe) public let gpiof = GPIOF(unsafeAddress: 0x40021400)

/// General-purpose I/Os
nonisolated(unsafe) public let gpiog = GPIOG(unsafeAddress: 0x40021800)

/// General-purpose I/Os
nonisolated(unsafe) public let gpioh = GPIOH(unsafeAddress: 0x40021c00)

// /// Reset and clock control
nonisolated(unsafe) public let rcc = RCC(unsafeAddress: 0x40023800)

// /// Universal synchronous asynchronous receiver transmitter
nonisolated(unsafe) public let usart1 = USART1(unsafeAddress: 0x40011000)